name: Super-Linter

# 新しいコミットがリポジトリにプッシュされるたびにこのワークフローを実行する
on: push

jobs:
  # ジョブキーを設定する。 ジョブ名が指定されていない場合、
  # キーはジョブ名として表示される
  super-lint:
    # ジョブ名を付ける
    name: Run rspec
    # 実行するマシンのタイプを設定する
    runs-on: ubuntu-latest

    steps:
      # ubuntu-latest マシンでリポジトリのコピーをチェックアウトする
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login GitHub Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u owner --password-stdin

      - name: Pull image from GitHub Registry
        run: docker pull docker.pkg.github.com/yuya2017/shogicom/shogicom_web:latest

      - name: Database configuration
        run: docker run docker.pkg.github.com/yuya2017/shogicom/shogicom_web:latest rails db:drop db:create db:migrate  RAILS_ENV=test

      - name: Run test
        run: bin/rspec
